--@block
SELECT * FROM users_normaluser;
--@block
CREATE TABLE "store_game" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "description" text NOT NULL, "release_date" date NOT NULL, "price" numeric(8, 2) NOT NULL, "cover_image" varchar(100) NULL, "developer_id" bigint NOT NULL);
--@block
ALTER TABLE "store_game" ADD CONSTRAINT "store_game_developer_id_7a837487_fk_users_gamedeveloper_id" FOREIGN KEY ("developer_id") REFERENCES "users_gamedeveloper" ("id") DEFERRABLE INITIALLY DEFERRED;
--@block
CREATE INDEX "store_game_developer_id_7a837487" ON "store_game" ("developer_id");
COMMIT;

--@block
CREATE TABLE "games_game" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "description" text NOT NULL, "release_date" date NOT NULL, "price" numeric(8, 2) NOT NULL, "cover_image" varchar(100) NULL, "developer_id" varchar(254) NOT NULL);
--@block
ALTER TABLE "games_game" ADD CONSTRAINT "games_game_developer_id_96377516_fk_users_gamedeveloper_email" FOREIGN KEY ("developer_id") REFERENCES "users_gamedeveloper" ("email") DEFERRABLE INITIALLY DEFERRED;
--@block
CREATE INDEX "games_game_developer_id_96377516" ON "games_game" ("developer_id");
--@block
CREATE INDEX "games_game_developer_id_96377516_like" ON "games_game" ("developer_id" varchar_pattern_ops);
--@block
COMMIT;
--@block
BEGIN;
--
-- Create model Cart
--
CREATE TABLE "store_cart" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" integer NOT NULL);
--
-- Create model Favorite
--
CREATE TABLE "store_favorite" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" integer NOT NULL);
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_game_id_9fdd6fd3_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_id_99e99107_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_cart_game_id_9fdd6fd3" ON "store_cart" ("game_id");
CREATE INDEX "store_cart_user_id_99e99107" ON "store_cart" ("user_id");
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_game_id_2e3d785a_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_id_0874cdc5_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_favorite_game_id_2e3d785a" ON "store_favorite" ("game_id");
CREATE INDEX "store_favorite_user_id_0874cdc5" ON "store_favorite" ("user_id");
COMMIT;