--@block
SELECT * FROM users_normaluser;
--@block
CREATE TABLE "store_game" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "description" text NOT NULL, "release_date" date NOT NULL, "price" numeric(8, 2) NOT NULL, "cover_image" varchar(100) NULL, "developer_id" bigint NOT NULL);
--@block
ALTER TABLE "store_game" ADD CONSTRAINT "store_game_developer_id_7a837487_fk_users_gamedeveloper_id" FOREIGN KEY ("developer_id") REFERENCES "users_gamedeveloper" ("id") DEFERRABLE INITIALLY DEFERRED;
--@block
CREATE INDEX "store_game_developer_id_7a837487" ON "store_game" ("developer_id");
COMMIT;