--@block
SELECT * FROM users_normaluser;
--@block
CREATE TABLE "store_game" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "description" text NOT NULL, "release_date" date NOT NULL, "price" numeric(8, 2) NOT NULL, "cover_image" varchar(100) NULL, "developer_id" bigint NOT NULL);
--@block
ALTER TABLE "store_game" ADD CONSTRAINT "store_game_developer_id_7a837487_fk_users_gamedeveloper_id" FOREIGN KEY ("developer_id") REFERENCES "users_gamedeveloper" ("id") DEFERRABLE INITIALLY DEFERRED;
--@block
CREATE INDEX "store_game_developer_id_7a837487" ON "store_game" ("developer_id");
COMMIT;

--@block
CREATE TABLE "games_game" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(100) NOT NULL, "description" text NOT NULL, "release_date" date NOT NULL, "price" numeric(8, 2) NOT NULL, "cover_image" varchar(100) NULL, "developer_id" varchar(254) NOT NULL);
--@block
ALTER TABLE "games_game" ADD CONSTRAINT "games_game_developer_id_96377516_fk_users_gamedeveloper_email" FOREIGN KEY ("developer_id") REFERENCES "users_gamedeveloper" ("email") DEFERRABLE INITIALLY DEFERRED;
--@block
CREATE INDEX "games_game_developer_id_96377516" ON "games_game" ("developer_id");
--@block
CREATE INDEX "games_game_developer_id_96377516_like" ON "games_game" ("developer_id" varchar_pattern_ops);
--@block
COMMIT;
--@block
BEGIN;
--
-- Create model Cart
--
CREATE TABLE "store_cart" ("user_email" varchar(254) NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
--
-- Create model Favorite
--
CREATE TABLE "store_favorite" ("user_email" varchar(254) NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_game_id_9fdd6fd3_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_id_99e99107_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_cart_user_email_c04942ab_like" ON "store_cart" ("user_email" varchar_pattern_ops);
CREATE INDEX "store_cart_game_id_9fdd6fd3" ON "store_cart" ("game_id");
CREATE INDEX "store_cart_user_id_99e99107" ON "store_cart" ("user_id");
CREATE INDEX "store_cart_user_id_99e99107_like" ON "store_cart" ("user_id" varchar_pattern_ops);
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_game_id_2e3d785a_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_id_0874cdc5_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_favorite_user_email_d7263f05_like" ON "store_favorite" ("user_email" varchar_pattern_ops);
CREATE INDEX "store_favorite_game_id_2e3d785a" ON "store_favorite" ("game_id");
CREATE INDEX "store_favorite_user_id_0874cdc5" ON "store_favorite" ("user_id");
CREATE INDEX "store_favorite_user_id_0874cdc5_like" ON "store_favorite" ("user_id" varchar_pattern_ops);
COMMIT;
--@block
BEGIN;
--
-- Remove field user from cart
--
SET CONSTRAINTS "store_cart_user_id_99e99107_fk_users_normaluser_email" IMMEDIATE; ALTER TABLE "store_cart" DROP CONSTRAINT "store_cart_user_id_99e99107_fk_users_normaluser_email";
ALTER TABLE "store_cart" DROP COLUMN "user_id" CASCADE;
--
-- Remove field user from favorite
--
SET CONSTRAINTS "store_favorite_user_id_0874cdc5_fk_users_normaluser_email" IMMEDIATE; ALTER TABLE "store_favorite" DROP CONSTRAINT "store_favorite_user_id_0874cdc5_fk_users_normaluser_email";
ALTER TABLE "store_favorite" DROP COLUMN "user_id" CASCADE;
--
-- Alter field user_email on cart
--
ALTER TABLE "store_cart" RENAME COLUMN "user_email" TO "user_email_id";
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_email_id_44946bae_fk_users_normaluser_email" FOREIGN KEY ("user_email_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field user_email on favorite
--
ALTER TABLE "store_favorite" RENAME COLUMN "user_email" TO "user_email_id";
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_email_id_3f8d8720_fk_users_normaluser_email" FOREIGN KEY ("user_email_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
--@block
DROP TABLE "store_cart";

--@block
DROP TABLE "store_favorite";

--@block
BEGIN;
--
-- Create model Cart
--
CREATE TABLE "store_cart" ("user_email" varchar(254) NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
--
-- Create model Favorite
--
CREATE TABLE "store_favorite" ("user_email" varchar(254) NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_game_id_9fdd6fd3_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_id_99e99107_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_cart_user_email_c04942ab_like" ON "store_cart" ("user_email" varchar_pattern_ops);
CREATE INDEX "store_cart_game_id_9fdd6fd3" ON "store_cart" ("game_id");
CREATE INDEX "store_cart_user_id_99e99107" ON "store_cart" ("user_id");
CREATE INDEX "store_cart_user_id_99e99107_like" ON "store_cart" ("user_id" varchar_pattern_ops);
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_game_id_2e3d785a_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_id_0874cdc5_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_favorite_user_email_d7263f05_like" ON "store_favorite" ("user_email" varchar_pattern_ops);
CREATE INDEX "store_favorite_game_id_2e3d785a" ON "store_favorite" ("game_id");
CREATE INDEX "store_favorite_user_id_0874cdc5" ON "store_favorite" ("user_id");
CREATE INDEX "store_favorite_user_id_0874cdc5_like" ON "store_favorite" ("user_id" varchar_pattern_ops);
COMMIT;

--@block
BEGIN;
--
-- Create model Cart
--
CREATE TABLE "store_cart" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_email" varchar(254) NOT NULL, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
--
-- Create model Favorite
--
CREATE TABLE "store_favorite" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_email" varchar(254) NOT NULL, "created_at" timestamp with time zone NOT NULL, "game_id" bigint NOT NULL, "user_id" varchar(254) NOT NULL);
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_email_game_id_1bc4d84b_uniq" UNIQUE ("user_email", "game_id");
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_game_id_9fdd6fd3_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_cart" ADD CONSTRAINT "store_cart_user_id_99e99107_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_cart_game_id_9fdd6fd3" ON "store_cart" ("game_id");
CREATE INDEX "store_cart_user_id_99e99107" ON "store_cart" ("user_id");
CREATE INDEX "store_cart_user_id_99e99107_like" ON "store_cart" ("user_id" varchar_pattern_ops);
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_email_game_id_e1763246_uniq" UNIQUE ("user_email", "game_id");
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_game_id_2e3d785a_fk_games_game_id" FOREIGN KEY ("game_id") REFERENCES "games_game" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_favorite" ADD CONSTRAINT "store_favorite_user_id_0874cdc5_fk_users_normaluser_email" FOREIGN KEY ("user_id") REFERENCES "users_normaluser" ("email") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_favorite_game_id_2e3d785a" ON "store_favorite" ("game_id");
CREATE INDEX "store_favorite_user_id_0874cdc5" ON "store_favorite" ("user_id");
CREATE INDEX "store_favorite_user_id_0874cdc5_like" ON "store_favorite" ("user_id" varchar_pattern_ops);
COMMIT;