# Generated by Django 5.0.4 on 2024-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedeveloper',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='company_url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='dob',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='employee_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='name',
            field=models.CharField(default='Game Dev', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='phoneno',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='phoneno',
            field=models.CharField(default='', max_length=15),
        ),
    ]
