# Generated by Django 5.0.4 on 2024-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gamedeveloper_password_normaluser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedeveloper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamedeveloper',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
