# Generated by Django 5.0.4 on 2024-04-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='game_covers/')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gamedeveloper')),
            ],
            options={
                'db_table': 'store_game',
            },
        ),
    ]
